// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/lyeslabs/mcpgen version v0.0.0-20250525235452-36324c43a471 DO NOT EDIT.
package apiclient

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// ArrowList Spceific information explaining a single type of arrow
type ArrowList struct {
	ASTtype *int    `json:"ASTtype,omitempty"`
	ArrPtr  *int    `json:"ArrPtr,omitempty"`
	ISTtype *int    `json:"ISTtype,omitempty"`
	InvL    *string `json:"InvL,omitempty"`
	InvPtr  *int    `json:"InvPtr,omitempty"`
	InvS    *string `json:"InvS,omitempty"`
	Long    *string `json:"Long,omitempty"`
	Short   *string `json:"Short,omitempty"`
}

// Arrows defines model for Arrows.
type Arrows = []ArrowList

// ChCtx defines model for ChCtx.
type ChCtx struct {
	Chapter *string `json:"Chapter,omitempty"`
	Common  *[]Loc  `json:"Common,omitempty"`
	Context *[]Loc  `json:"Context,omitempty"`
	Single  *[]Loc  `json:"Single,omitempty"`

	// XYZ The coordinates of the node, relative to a search in 3d semantic spacetime
	XYZ *Coords `json:"XYZ,omitempty"`
}

// ConePaths A structure listing paths from a root node
type ConePaths struct {
	// BTWC An array of Betweenness Centrality scores for the path matrix
	BTWC *[]string `json:"BTWC,omitempty"`

	// Paths An array of paths starting from the root node
	Paths *[][]WebPath `json:"Paths,omitempty"`

	// RootNode An internal direct reference to a knowable item
	RootNode *NodePtr `json:"RootNode,omitempty"`

	// SuperNodes A list of nodes identified by their symmetrical roles in the paths
	SuperNodes *[]string `json:"SuperNodes,omitempty"`

	// Title The text of the root node
	Title *string `json:"Title,omitempty"`
}

// Coords The coordinates of the node, relative to a search in 3d semantic spacetime
type Coords struct {
	Lat *float32 `json:"Lat,omitempty"`
	Lon *float32 `json:"Lon,omitempty"`
	R   *float32 `json:"R,omitempty"`
	X   *float32 `json:"X,omitempty"`
	Y   *float32 `json:"Y,omitempty"`
	Z   *float32 `json:"Z,omitempty"`
}

// Loc defines model for Loc.
type Loc struct {
	Reln *[]int  `json:"Reln,omitempty"`
	Text *string `json:"Text,omitempty"`

	// XYZ The coordinates of the node, relative to a search in 3d semantic spacetime
	XYZ *Coords `json:"XYZ,omitempty"`
}

// NodeEvent The content pointed to by a NodePtr
type NodeEvent struct {
	// Chap The chapter containing the text
	Chap *string `json:"Chap,omitempty"`

	// Context The context keywords explaining the relevance of the text
	Context *string `json:"Context,omitempty"`

	// L The string length of the text
	L *int `json:"L,omitempty"`

	// NPtr An internal direct reference to a knowable item
	NPtr *NodePtr `json:"NPtr,omitempty"`

	// Text The knowable data
	Text *string `json:"Text,omitempty"`

	// XYZ The coordinates of the node, relative to a search in 3d semantic spacetime
	XYZ *Coords `json:"XYZ,omitempty"`
}

// NodePtr An internal direct reference to a knowable item
type NodePtr struct {
	CPtr  *int `json:"CPtr,omitempty"`
	Class *int `json:"Class,omitempty"`
}

// Orbit An element in orbit around the knowable text
type Orbit struct {
	// Arrow The arrow type relating the orbiting item to the base knowable text
	Arrow *string `json:"Arrow,omitempty"`

	// Ctx The context key words of the orbiting item
	Ctx *string `json:"Ctx,omitempty"`

	// Dst An internal direct reference to a knowable item
	Dst *NodePtr `json:"Dst,omitempty"`

	// OOO The coordinates of the node, relative to a search in 3d semantic spacetime
	OOO *Coords `json:"OOO,omitempty"`

	// Radius The distance of the related item from the base knowable text
	Radius *int `json:"Radius,omitempty"`

	// STindex The Semantic Spacetime type (0-6) of the arrow
	STindex *int `json:"STindex,omitempty"`

	// Text The dereferenced text of the orbiting item
	Text *string `json:"Text,omitempty"`

	// Wgt The link weight of the arrow
	Wgt *float32 `json:"Wgt,omitempty"`

	// XYZ The coordinates of the node, relative to a search in 3d semantic spacetime
	XYZ *Coords `json:"XYZ,omitempty"`
}

// Orbits An array of nearest neighbours of the selected knowable text
type Orbits = [][]Orbit

// PageMap A literal rendering of the original N4L page notes
type PageMap struct {
	// Context The context keywords labelling the knowable item
	Context *string `json:"Context,omitempty"`

	// Notes An array of the related notes matching the knowable item
	Notes *[][]WebPath `json:"Notes,omitempty"`

	// Title The knowable item
	Title *string `json:"Title,omitempty"`
}

// PathSolve A structure listing paths from a root node
type PathSolve struct {
	// BTWC An array of Betweenness Centrality scores for the path matrix
	BTWC *[]string `json:"BTWC,omitempty"`

	// Paths An array of paths starting from the root node
	Paths *[][]WebPath `json:"Paths,omitempty"`

	// RootNode An internal direct reference to a knowable item
	RootNode *NodePtr `json:"RootNode,omitempty"`

	// SuperNodes A list of nodes identified by their symmetrical roles in the paths
	SuperNodes *[]string `json:"SuperNodes,omitempty"`

	// Title The text of the root node
	Title *string `json:"Title,omitempty"`
}

// Sequence An array of NodeEvents forming a story sequence about the search topic
type Sequence = []NodeEvent

// TOC A table of contents matching chapters and contexts
type TOC = []ChCtx

// WebPath A curated journey through the knowable graph
type WebPath struct {
	// Arr The arrow type of the next leg of the path
	Arr *int `json:"Arr,omitempty"`

	// Chp The chapter the text belongs to
	Chp *string `json:"Chp,omitempty"`

	// Ctx The context keywords the text belongs to
	Ctx *string `json:"Ctx,omitempty"`

	// Line The line number reference of the text in the original N4L notes
	Line *int `json:"Line,omitempty"`

	// NPtr An internal direct reference to a knowable item
	NPtr *NodePtr `json:"NPtr,omitempty"`

	// Name The text for this location in the path
	Name *string `json:"Name,omitempty"`

	// STindex The Semantic Spacetime (0-6) type of the arrow
	STindex *int `json:"STindex,omitempty"`

	// Wgt The weight assigned to the arrow link
	Wgt *float32 `json:"Wgt,omitempty"`

	// XYZ The coordinates of the node, relative to a search in 3d semantic spacetime
	XYZ *Coords `json:"XYZ,omitempty"`
}

// N4LqueryFormdataBody defines parameters for N4Lquery.
type N4LqueryFormdataBody struct {
	// Chapcontext string used for web group updates
	Chapcontext *string `form:"chapcontext,omitempty" json:"chapcontext,omitempty"`

	// Name A search string in the N4L query language
	Name string `form:"name" json:"name"`

	// Nclass NPtr string classification for direct lookup
	Nclass *string `form:"nclass,omitempty" json:"nclass,omitempty"`

	// Ncptr NPtr hash number for direct lookup
	Ncptr *string `form:"ncptr,omitempty" json:"ncptr,omitempty"`
}

// N4LqueryFormdataRequestBody defines body for N4Lquery for application/x-www-form-urlencoded ContentType.
type N4LqueryFormdataRequestBody N4LqueryFormdataBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// N4LqueryWithBody request with any body
	N4LqueryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	N4LqueryWithFormdataBody(ctx context.Context, body N4LqueryFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) N4LqueryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewN4LqueryRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) N4LqueryWithFormdataBody(ctx context.Context, body N4LqueryFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewN4LqueryRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewN4LqueryRequestWithFormdataBody calls the generic N4Lquery builder with application/x-www-form-urlencoded body
func NewN4LqueryRequestWithFormdataBody(server string, body N4LqueryFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewN4LqueryRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewN4LqueryRequestWithBody generates requests for N4Lquery with any type of body
func NewN4LqueryRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/searchN4L")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// N4LqueryWithBodyWithResponse request with any body
	N4LqueryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*N4LqueryResponse, error)

	N4LqueryWithFormdataBodyWithResponse(ctx context.Context, body N4LqueryFormdataRequestBody, reqEditors ...RequestEditorFn) (*N4LqueryResponse, error)
}

type N4LqueryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Content  *N4Lquery_200_Content `json:"Content,omitempty"`
		Response *string               `json:"Response,omitempty"`
	}
}
type N4Lquery_200_Content struct {
	union json.RawMessage
}

// Status returns HTTPResponse.Status
func (r N4LqueryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r N4LqueryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// N4LqueryWithBodyWithResponse request with arbitrary body returning *N4LqueryResponse
func (c *ClientWithResponses) N4LqueryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*N4LqueryResponse, error) {
	rsp, err := c.N4LqueryWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseN4LqueryResponse(rsp)
}

func (c *ClientWithResponses) N4LqueryWithFormdataBodyWithResponse(ctx context.Context, body N4LqueryFormdataRequestBody, reqEditors ...RequestEditorFn) (*N4LqueryResponse, error) {
	rsp, err := c.N4LqueryWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseN4LqueryResponse(rsp)
}

// ParseN4LqueryResponse parses an HTTP response from a N4LqueryWithResponse call
func ParseN4LqueryResponse(rsp *http.Response) (*N4LqueryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &N4LqueryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Content  *N4Lquery_200_Content `json:"Content,omitempty"`
			Response *string               `json:"Response,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
